/* Automatically generated by './build/update-component-index-file.js' */
import TabBar from './tab-bar';

const components = [
  TabBar
];

const install = function install(Vue) {
  components.forEach((component) => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
  TabBar
};
